### ISSUE TITLE
Improve Dockerfile

### ISSUE THREAD

**Issue by florianhartung** [ChiliGreenhouse/webapp#4]
In the frontend Dockerfile we do not want to serve the static page with `npm run preview` anymore.
This makes the docker image unnecessarily large.
Please use a lightweight static site server like [goStatic](https://github.com/PierreZ/goStatic) instead.

**Comment by kmprs** [comment]
The goStatic server cannot be used due to an issue with the reactjs router. Nginx might be another solution for this problem. 
See https://community.fly.io/t/how-to-fix-404-error-when-accessing-a-specific-url-for-create-react-apps-client-side-routing/7229
